default:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET_NAME') }}"
      threads: 1
      keyfile: "{{ env_var('SERVICE_ACCOUNT_KEYFILE_PATH') }}"
      timeout_seconds: 300
  target: dev
