version: 2

models:
  - name: stg_raw_data
    columns:
      - name: artist_name
        tests:
          - not_null
          - unique
      - name: track_name
        tests:
          - not_null
      - name: date
        tests:
          - not_null

  - name: dim_artist
    columns:
      - name: artist_id
        tests:
          - not_null
          - unique
      - name: artist_name
        tests:
          - not_null

  - name: dim_track
    columns:
      - name: track_id
        tests:
          - not_null
          - unique
      - name: track_name
        tests:
          - not_null

  - name: dim_playlist
    columns:
      - name: playlist_id
        tests:
          - not_null
          - unique
      - name: playlist_name
        tests:
          - not_null

  - name: fact_artist_chart_ranking
    columns:
      - name: artist_id
        tests:
          - not_null
      - name: chart_id
        tests:
          - not_null
      - name: chart_position
        tests:
          - not_null

  - name: fact_track_chart_ranking
    columns:
      - name: track_id
        tests:
          - not_null
      - name: chart_id
        tests:
          - not_null
      - name: chart_position
        tests:
          - not_null

  - name: fact_playlist_tracks
    columns:
      - name: playlist_id
        tests:
          - not_null
      - name: track_id
        tests:
          - not_null
